version: "3"

services:
  mariadb:
    build: requirements/mariadb/
    container_name: my_mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
      - 3306:3306
    networks:
      - my_network
    volumes:
      - db:/var/lib/mysql

  wordpress:
    build: requirements/wordpress/
    container_name: my_wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - 9000:9000
    networks:
      - my_network
    volumes:
      - wordpress_shared:/var/www/html/
    depends_on:
      - mariadb
  nginx:
    build: requirements/nginx/
    container_name: my_nginx
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - wordpress_shared:/var/www/html/
    networks:
      - my_network
    depends_on:
      - wordpress



networks:
  my_network:
    driver: bridge

volumes:
  wordpress_shared: {}
  db: {}
